### PR TITLE
Update Chinese Translation

### LINKED ISSUE #129: BUG: 中文翻译问题
## 描述问题
这几个地方，没有翻译成中文？我已经标注，请修复。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

### PR DESCRIPTION
**Pull request by oarinv**
This Pull Request updates the Chinese translations in the project. Please review the changes and let me know if any adjustments are needed.

Related Issue:

Fixes #129

### CODE REVIEW

**Comment by Mahdi-zarei** [comment]
Thank you very much for your contribution!

**Comment by oarinv** [comment]
In 240 line,have tow translation tag

**Comment by Mahdi-zarei** [comment]
will fix it for the release

**Comment by cnm4399** [comment]
> 此 Pull Request 更新了项目中的中文翻译。请查看更改并告知我是否需要任何调整。
> 
> 相关问题：
> 
> 修复 [#129 ](https://github.com/Mahdi-zarei/nekoray/issues/129)

**感谢你的热心付出，4.1.5版本我已下载和检查，发现几处翻译错误和无翻译的选项，我用图片标注出来，请修复！！**
****

**Pull request merged**
